jaffle_shop_demo_1:
  outputs:
    data:
      type: sqlserver
      server: "127.0.0.1"
      database: "sql_database_demo1"
      schema: "dbo"
      user: "sa"
      password: "Password123"
      port: 1437 
      driver: "ODBC Driver 18 for SQL Server"
      trust_cert: true
      threads: 1
  target: data

jaffle_shop_demo_2:
  outputs:
    data:
      type: sqlserver
      server: "127.0.0.1"
      database: "sql_database_demo2"
      schema: "dbo"
      user: "sa"
      password: "Password123"
      port: 1437 
      driver: "ODBC Driver 18 for SQL Server"
      trust_cert: true
      threads: 1
  target: data
