sqlserver_local_profile:
  outputs:
    data:
      type: sqlserver
      server: localhost
      database: sql_coredata
      schema: dbo
      user: sa
      password: 'YourStrong@Passw0rd'
      port: 1437
      driver: "ODBC Driver 18 for SQL Server"
      trust_cert: true
      threads: 16
  target: data